<?php
/**
 * TL_ROOT/system/modules/pageimage/languages/lv/modules.php 
 * 
 * Contao extension: pageimage 1.2.2 stable 
 * Latvian translation file 
 * 
 * Copyright : © 2009-2011 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['pageImage']['0'] = "Lapas attēls";
$GLOBALS['TL_LANG']['FMD']['pageImage']['0'] = "Lapas attēls";
$GLOBALS['TL_LANG']['FMD']['pageImage']['1'] = "Ļauj iestatīt attēlu katrā lapā un parādīt to frontend-ā. Attēlus var pārmantot no augstākstāvošas (parent)lapas.";
 
?>
