<?php
/**
 * TL_ROOT/system/modules/pageimage/languages/lv/tl_module.php 
 * 
 * Contao extension: pageimage 1.2.2 stable 
 * Latvian translation file 
 * 
 * Copyright : © 2009-2011 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['inheritPageImage']['0'] = "Lietot augstākas lapas (parent) attēlu";
$GLOBALS['TL_LANG']['tl_module']['inheritPageImage']['1'] = "Lietot attēlu no augstākstāvošas lapas, ja konkrētajai lapai nav attēlu.";
 
?>
