<?php
/**
 * TL_ROOT/system/modules/pageimage/languages/lv/tl_page.php 
 * 
 * Contao extension: pageimage 1.2.2 stable 
 * Latvian translation file 
 * 
 * Copyright : © 2009-2011 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Maris Celmins (warrior), http://www.bauskasbiblioteka.lv 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_page']['pageImage']['0'] = "Attēls konkrētajai lapai";
$GLOBALS['TL_LANG']['tl_page']['pageImage']['1'] = "Lūdzu, izvēlieties attēlu konkrētajai lapai. Ja jūs neizvēlēties neko, tad var tikt izmantots augstākstāvošas (parent) lapas attēls.";
$GLOBALS['TL_LANG']['tl_page']['pageImageJumpTo']['0'] = "Attēla-saite konkrētajai lapai";
$GLOBALS['TL_LANG']['tl_page']['pageImageJumpTo']['1'] = "Jūs varat pievienot saiti uz citu Contao lapu, kad uzklikšķiniet uz attēla.";
$GLOBALS['TL_LANG']['tl_page']['pageImageAlt']['0'] = "Alternatīvs teksts";
$GLOBALS['TL_LANG']['tl_page']['pageImageAlt']['1'] = "Pieejama tīmekļa vietne vienmēr sniedz attēlus ar alternatīvu tekstu, krā ir īss aprakstu par attēla saturu.";
$GLOBALS['TL_LANG']['tl_page']['pageImageTitle']['0'] = "Saites nosaukums";
$GLOBALS['TL_LANG']['tl_page']['pageImageTitle']['1'] = "Ievadiet saites nosaukumu. Ja jūs nenorādiet nosaukumu, tiks izmantots mērķa lapas nosaukums.";
$GLOBALS['TL_LANG']['tl_page']['image_legend'] = "Lapas attēls";
 
?>
