<?php
/**
 * TL_ROOT/system/modules/pageimage/languages/uk/modules.php 
 * 
 * Contao extension: pageimage 1.2.1 stable 
 * Ukrainian translation file 
 * 
 * Copyright : © 2009-2010 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Sergey Dyagovchenko (DyaGa), http://d.sumy.ua/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['pageImage']['0'] = "Зображення сторінки";
$GLOBALS['TL_LANG']['FMD']['pageImage']['0'] = "Зображення сторінки";
$GLOBALS['TL_LANG']['FMD']['pageImage']['1'] = "Дозволяє прив'язувати зображення до сторінок сайту. Зображення можуть бути успадковані від батьківських старніцах.";
 
?>
