<?php
/**
 * TL_ROOT/system/modules/pageimage/languages/uk/tl_page.php 
 * 
 * Contao extension: pageimage 1.2.1 stable 
 * Ukrainian translation file 
 * 
 * Copyright : © 2009-2010 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Sergey Dyagovchenko (DyaGa), http://d.sumy.ua/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_page']['pageImage']['0'] = "Зображення сторінки";
$GLOBALS['TL_LANG']['tl_page']['pageImage']['1'] = "Виберіть зображення сторінки. Якщо зображення не вибрано, то можливо успадкування зображення від батьківської сторінки.";
$GLOBALS['TL_LANG']['tl_page']['pageImageJumpTo']['0'] = "Посилання на сторінку";
$GLOBALS['TL_LANG']['tl_page']['pageImageJumpTo']['1'] = "Виберіть сторінку на яку буде перенаправлено користувача при кліці на зображенні.";
$GLOBALS['TL_LANG']['tl_page']['pageImageAlt']['0'] = "Альтернативний текст";
$GLOBALS['TL_LANG']['tl_page']['pageImageAlt']['1'] = "Введіть короткий опис зображення.";
$GLOBALS['TL_LANG']['tl_page']['pageImageTitle']['0'] = "Текст посилання";
$GLOBALS['TL_LANG']['tl_page']['pageImageTitle']['1'] = "Введіть текст посилання. Якщо поле залишити порожнім, то в якості тексту буде використано назву сторінки на яку вказує посилання.";
$GLOBALS['TL_LANG']['tl_page']['image_legend'] = "Зображення сторінки";
 
?>
