<?php
/**
 * TL_ROOT/system/modules/pageimage/languages/ru/tl_module.php 
 * 
 * Contao extension: pageimage 1.2.1 stable 
 * Russian translation file 
 * 
 * Copyright : © 2009-2010 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Sergey Dyagovchenko (DyaGa), http://d.sumy.ua/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['inheritPageImage']['0'] = "Наследование изображения";
$GLOBALS['TL_LANG']['tl_module']['inheritPageImage']['1'] = "Если связаного изображения с активной страницей нет, то будет унаследовано изображение от родительской страницы.";
 
?>
