<?php
/**
 * TL_ROOT/system/modules/pageimage/languages/ru/tl_page.php 
 * 
 * Contao extension: pageimage 1.2.1 stable 
 * Russian translation file 
 * 
 * Copyright : © 2009-2010 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Sergey Dyagovchenko (DyaGa), http://d.sumy.ua/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_page']['pageImage']['0'] = "Изображение страницы";
$GLOBALS['TL_LANG']['tl_page']['pageImage']['1'] = "Выберите изображение страницы. Если изображение не выбрано, то возможно наследование изображения от родительской страницы.";
$GLOBALS['TL_LANG']['tl_page']['pageImageJumpTo']['0'] = "Ссылка на страницу";
$GLOBALS['TL_LANG']['tl_page']['pageImageJumpTo']['1'] = "Выберите страницу на которую будет перенаправлен пользователь при клике на изображении.";
$GLOBALS['TL_LANG']['tl_page']['pageImageAlt']['0'] = "Альтернативный текст";
$GLOBALS['TL_LANG']['tl_page']['pageImageAlt']['1'] = "Введите краткое описание изображения.";
$GLOBALS['TL_LANG']['tl_page']['pageImageTitle']['0'] = "Текст ссылки";
$GLOBALS['TL_LANG']['tl_page']['pageImageTitle']['1'] = "Введите текст ссылки. Если поле оставить пустым, то в качестве текста будет использовано название страницы на которую указывает ссылка.";
$GLOBALS['TL_LANG']['tl_page']['image_legend'] = "Изображение страницы";
 
?>
